import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

// design of app inspired by https://www.figma.com/community/file/1006124254408605916/mobile-banking

export const metadata = {
  title: "Chas Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`z-40 min-h-screen font-montserrat bg-[rgb(18,20,51)] text-white lg:text-[20px]`}>

    {/* <div className="hidden md:block">

      <TopBar stickyOrFixed={"sticky"}></TopBar>
    </div> */}
        
          {children}
       
       {/* <div className="mt-20 sticky ">
       <NavBar stickyOrFixed={"fixed"}></NavBar>
       </div> */}
      </body>
    </html>
  );
}
